### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by AndyTaylorTweet** [juribeparada/MMDVM_CM#1]
DMR2NXDN - Works great, also have it working via DMRGateway too, no issues here, occasional ring buffer issues but that may also be happening on the NXDNGateway, I have not looked.

DMR2YSF - Can you do anything to add the ability to request reflector changes based on the DMR TG?

YSF2NXDN/YSF2DMR/YSF2P25 - All work nicely, again - any way to choose the target TG from the YSF radio?

Over-all - oustanding work, and all pulled into Pi-Star apart from NXDN2DMR

**Comment by juribeparada** [comment]
Hi Andy, thank you for add DMR2YSF and DMR2NXDN very quickly.

I will add to DMR2YSF (I think soon) the reflector selection using DMR TG, probably using a txt file with TG <-> Reflector mapping.

Regarding YSF2NXDN/YSF2DMR/YSF2P25, all they can select the target TG using the radio, but must be connected directly to MMDVMHost. This is because YSFGateway processes all Wires-X first. I think we need a large modification to YSFGateway for a better integration of all these programs.

**Comment by AndyTaylorTweet** [comment]
For DMR2YSF;
In case it helps I already have FCS and YSF host files:
http://www.pistar.uk/downloads/YSF_Hosts.txt
http://www.pistar.uk/downloads/FCS_Hosts.txt

you may consider mapping all FCS to 99nnn to keep them all 5 digit numbers (I'd find that handy), because then I can keep my DMRGateway setup (7nnnnn is forwarded to DMR2YSF on Pi-Star), although we can always work with whatever you end up with :)

As for the YSF2xxx, no great ideas with those yet :)

**Comment by juribeparada** [comment]
Hi Andy, finally I decided to add TGList support for DMR2YSF, this will give more flexibility for the users. Please check the new MMDVM_CM version.

Regards,
Andy CA6JAU

**Comment by AndyTaylorTweet** [comment]
Thank you Andy, I'll pull those in over the next couple of days.

**Comment by AndyTaylorTweet** [comment]
Here is a DMR map for every YSF destination:

http://www.pistar.uk/downloads/TGList_YSF.txt

Not sure if the FCS will work yet - I'll be testing that shortly.

**Comment by juribeparada** [comment]
Looking at your list, you can not use "names" for FCS reflectors, you need to use IDs (numbers) also.

**Comment by AndyTaylorTweet** [comment]
The current YSFGateway uses the names and not the numbers to connect; I may have to just remove the FCS refs for now - those dong have numbers.

**Comment by juribeparada** [comment]
Yes, your are right, but I am using numbers becase the Wires-X system always uses numbers internally to connect to a room. YSFGateway associate a number for each FCS reflector. I will need to find a way to use names.

**Comment by juribeparada** [comment]
Hi Andy, you can use your original "TGList_YSF.txt" file for DMR2YSF, now will recognize correctly the FCS rooms.
