### ISSUE TITLE
WiresX.cpp compier warning

### ISSUE THREAD

**Issue by AndyTaylorTweet** [juribeparada/MMDVM_CM#10]
`g++ -g -O3 -Wall -std=c++0x -pthread -c -o WiresX.o WiresX.cpp
WiresX.cpp: In member function ‘CTGReg* CWiresX::findById(unsigned int)’:
WiresX.cpp:887:10: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (id == atoi((*it)->m_id.c_str()))
       ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~`

This happens wherever WiresX.cpp is compiled, its only a compiler warning, but needs to be cleaned up.

**Comment by juribeparada** [comment]
It should be fixed now
