### ISSUE TITLE
YSF2xxx Make all WiresX output UPPERCASE

### ISSUE THREAD

**Issue by AndyTaylorTweet** [juribeparada/MMDVM_CM#13]
Andy, you are likely to want to implement the same fix as this for your YSF2xxx modes.

https://github.com/g4klx/YSFClients/commit/013de54c5a04628f094aac8b72af802a5f0be8c5

Many YSF radios are unable to handle lower case YSF lists, even if they do handle them, searches are always upper case.

**Comment by juribeparada** [comment]
Added upper case for all YSF2XXX. I only tested with YSF2DMR, using macOS as usual.

**Comment by AndyTaylorTweet** [comment]
Thank you, the host files that Pi-Star uses have been modified to mitigate the requirement, but this is a good thing going forwards - it helps on some of the newer radios (FT70d etc).
