### ISSUE TITLE
MMDVM_CM/YSF2P25/YSF2P25.cpp - no SendP25Ptt code

### ISSUE THREAD

**Issue by AndyTaylorTweet** [juribeparada/MMDVM_CM#14]
The code block for sendP25Ptt is currently empty, are there any plans to add this?
Is there anything I can do to help with this? - Although it might well take you longer to teach me than to add it in :)

**Comment by juribeparada** [comment]
I remember it was not totally necessary to add sendP25PTT(). Why do you think it is necessary?, what feature do you expect?

**Comment by AndyTaylorTweet** [comment]
I specifically want to be able to unlink via WiresX (this relates actually to something else I am working on - I'll mail you about that separately).

It's not exactly required, but it is desirable, specifically - the user *can* send a link to TG9999, but having WiresX do that on unlink would be much more desirable.

**Comment by juribeparada** [comment]
I will implement when I find some free time for that.

**Comment by AndyTaylorTweet** [comment]
Works great, thank you, see #15 for a small improvement to connect on like and get the voice feedback.

One more feature I would love to see, is to have the WiresX link also drive the radio to swap to VW mode (so that you don't have to drop/re-link).

DN is 01, VW is 10, but I don't know where exactly these bits are set in the WiresX replies, when the VW voice comes in, my radio automatically swaps mode, BUT while in WiresX mode, it will ALWAYS TX in DN - this may not be a thing that can be set in the WiresX reply, but it would be nice if it is.
