### ISSUE TITLE
DMR2YSF startup at TG0

### ISSUE THREAD

**Issue by narspt** [juribeparada/MMDVM_CM#3]
Hi Andy, Is it intended or is there any specific reason for DMR2YSF startup TG being TG0? (i.e. before we transmit on DMR side for the 1st time)

I guess you may plan to add code on future to change rooms using TGs, anyway in the mean time maybe it would be better to startup it at TG1 or some other TG that can be heard by all radios?

**Comment by juribeparada** [comment]
OK, changed, but not sure if this will be useful

**Comment by narspt** [comment]
Well my idea is that if it defaults to TG0 then some radios (at least my Hytera) apparently haves no way really to listen it at all, then it did require I always key PTT at DMR side so that DMR2YSF starts using an usable TG. Instead if it defaults to TG1 then I just need to set my radio to TG1 and I can immediately start listening without the need to always key PTT.
