### ISSUE TITLE
YSF2DMR Missing audio in YSF Radio

### ISSUE THREAD

**Issue by VE3RD** [juribeparada/MMDVM_CM#31]
When running pi-star 3.4.17 the following is not an issue, everything works just fine

When I flashed pi-star 4.1.0 and setup YSF2DMR I got the following issues
1) Transmissions from c4fm to dmr worked just fine
2) Transmissions from dmr to c4fm failed. RF was received by the radio but the  audio was not decoded.
3) Wires X Pass through was ON
4) I ssh'd into  pi-star and edited /etc/ysf2dmr and set EnableWiresX from 1 to 0, restarted ysf2dmr service and the radio came alive with audio, unfortunately wiresX no longer functioned on the radio
5) I reset the EnableWiresX tfrom 0 to 1 and the radio audio stopped.

I toggled this enablewiresx parameter back and forth many times and got the exact same results
Phil VE3RD

**Comment by AndyTaylorTweet** [comment]
PR #32 submitted to address this.
