### ISSUE TITLE
YSF2DMR not compling

### ISSUE THREAD

**Issue by m0glj** [juribeparada/MMDVM_CM#34]
<quote>
root@vps-4a62c445:~/MMDVM_CM# make

make -C DMR2NXDN

make[1]: Entering directory '/root/MMDVM_CM/DMR2NXDN'

make[1]: Nothing to be done for 'all'.

make[1]: Leaving directory '/root/MMDVM_CM/DMR2NXDN'

make -C DMR2YSF

make[1]: Entering directory '/root/MMDVM_CM/DMR2YSF'

make[1]: Nothing to be done for 'all'.

make[1]: Leaving directory '/root/MMDVM_CM/DMR2YSF'

make -C NXDN2DMR

make[1]: Entering directory '/root/MMDVM_CM/NXDN2DMR'

make[1]: Nothing to be done for 'all'.

make[1]: Leaving directory '/root/MMDVM_CM/NXDN2DMR'

make -C YSF2DMR

make[1]: Entering directory '/root/MMDVM_CM/YSF2DMR'

g++ -g -O3 -Wall -std=c++0x -pthread -c -o Conf.o Conf.cpp
In file included from Conf.cpp:21:0:

Conf.h:57:18: error: ‘unsigned char* CConf::getYsfDT1()’ cannot be overloaded
   unsigned char* getYsfDT1();
                  ^~~~~~~~~

Conf.h:54:30: error: with ‘std::vector<unsigned char> CConf::getYsfDT1()’
   std::vector<unsigned char> getYsfDT1();
                              ^~~~~~~~~

Conf.h:58:18: error: ‘unsigned char* CConf::getYsfDT2()’ cannot be overloaded
   unsigned char* getYsfDT2();
                  ^~~~~~~~~

Conf.h:55:30: error: with ‘std::vector<unsigned char> CConf::getYsfDT2()’
   std::vector<unsigned char> getYsfDT2();
                              ^~~~~~~~~

Conf.h:59:17: error: ‘char* CConf::getYsfRadioID()’ cannot be overloaded
   char*         getYsfRadioID();
                 ^~~~~~~~~~~~~

Conf.h:56:16: error: with ‘std::__cxx11::string CConf::getYsfRadioID()’
   std::string  getYsfRadioID();
                ^~~~~~~~~~~~~

Makefile:20: recipe for target 'Conf.o' failed

make[1]: *** [Conf.o] Error 1

make[1]: Leaving directory '/root/MMDVM_CM/YSF2DMR'

Makefile:7: recipe for target 'YSF2DMR' failed

make: *** [YSF2DMR] Error 2

root@vps-4a62c445:~/MMDVM_CM# 
</quote>

**Comment by AndyTaylorTweet** [comment]
PR coming

**Comment by AndyTaylorTweet** [comment]
PR submitted / pulled and tested. The code now compiles clean again - you just need to "git pull" to bring your local copy up to date, then "make clean" and "make" again and you should be in good shape.

**Comment by m0glj** [comment]
Complies Now
