### ISSUE TITLE
P252DMR Seg Fault on XLX

### ISSUE THREAD

**Issue by K2IE** [juribeparada/MMDVM_CM#46]
Trying to get P252DMR working with my XLX.  When I add the XLX parms to the .ini, running always results in a seg fault.  Here is the [DMR Network] stanta:

[DMR Network]
Id=1234567
XLXFile=/usr/local/etc/XLXHosts.txt
XLXModule=B
XLXReflector=020
#StartupDstId=4002
#StartupPC=1
#Address=xlx020.k2ie.net
Port=62030
Jitter=500
Password=PASSWORD
Debug=0

If I take out the XLX parms and uncomment the address, P252DMR will run, it will connect to the XLX, but not to any module.

**Comment by 9V1LH** [comment]
Same issue here. Haven't found a working solution so far. NXDN2DMR works like a charm.

**Comment by K2IE** [comment]
Seems to have been resolved by #49
