### ISSUE TITLE
YSF2DMR no callsign fresh compile

### ISSUE THREAD

**Issue by BrianWiegold** [juribeparada/MMDVM_CM#48]
I am currently putting a new Raspberry Pi image together (Buster), and after much head scratching I cannot get callsign/DMRid information to show on the YSF radio. I appreciate there are many configuration options that could affect the function of this and I have worked through them with no joy.
However, simply substituting the current YSF2DMR binary (and only the binary) for one borrowed from a Pi-Star 20200503  image all is well, there are no issues during the compilation process and I am compiling on the Pi.
Thanks in advance
Brian Wiegold

**Comment by AndyTaylorTweet** [comment]
Brian, I don't think this is a problem any more (so long as your config files are also correct), check yours against the one in this repo.

de MW0MWZ
