### ISSUE TITLE
Cannot access saved rooms through Wires-X on FT1XDR

### ISSUE THREAD

**Issue by gergles** [juribeparada/MMDVM_CM#5]
I can successfully search for YSF rooms and save them to my HT's memory through YSFGateway running on a pi-star (YSFGateway-20180802_Pi-Star), but if I attempt to access the saved rooms through the memory function, the radio transmits for a moment then fails. I select a category from the list, the radio TXs, but I am never shown the list of rooms to select from.

The logs show an Unknown Wires-X command I have reproduced below. This is an FT1XDR, firmware 13.01, DSP 4.15. To be clear, this occurs when holding down ENT, then selecting any category. I never even get to see the list of saved rooms – but I know they were properly saved because I can delete them from the HT's menu interface. I just can't seem to open the list/connect to one.

```
==> YSFGateway-2018-09-05.log <==
M: 2018-09-05 01:25:12.716 Unknown Wires-X command
M: 2018-09-05 01:25:12.718 0000:  06 5D 67 5F 24 30 30 20 20 20 30 32 30 32 30 33    *.]g_$00   020203*
M: 2018-09-05 01:25:12.719 0010:  34 36 34 32 33 30 03 6A 00 00 00 00 00 00 00 00    *464230.j........*
M: 2018-09-05 01:25:12.720 0020:  00 00 00 00 00 00 00 00                            *........*
```

**Comment by juribeparada** [comment]
Hi, are you using my last changes in YSFGateway with Wires-X Categories support?, be aware if you are using Pi-Star, Andy Taylor still haven't updated YSFGateway.

**Comment by gergles** [comment]
You're correct, I was using an older version of YSFGateway - I was thinking it was built on 2018-09-02 (which is the 'dashboard' version and newer than the latest commit), but the date on the filesystem is only 2018-08-02.

I cross-compiled YSFGateway from 2e506ce and categories work. 

The only remaining issue is that after selecting a room (from a category, or the search,) if the room is busy (i.e. someone is TXing while I try to join,) the audio starts playing from that room and the Pi-Star dashboard/YSFGateway logs shows that the room has changed, but the radio doesn't confirm joining the new room (it eventually times out the join attempt) and the old room name stays displayed on the HT. If I go back several times to get back to the standby screen, I can TX in that room with no issue, and the correct callsigns appear but the HT display still shows the incorrect room name.

I can replicate this 100% of the time with Alabama-Link (02034) **if** someone is talking at the moment I try to join, but I don't see the behavior with YSF2DMR, even though I am joined to TG 91 on YSF2DMR which is always busy too. My uneducated guess is some sort of race condition with sending the "you joined" confirmation to the radio and starting to send channel audio.

**Comment by juribeparada** [comment]
Well, that is a YSFGateway issue. That software still have small issues like this, I'm trying to fix one by one when I have some spare time. I will add this remaining issue to my list.

**Comment by juribeparada** [comment]
I will close this issue since the main problem is solved. Also, the commented problem is a YSFGateway issue and not a MMDVM_CM problem.
