### ISSUE TITLE
P252DMR fails to build

### ISSUE THREAD

**Issue by K2IE** [juribeparada/MMDVM_CM#61]
I suspect that this is related to the change in commit 89a9dd6017263efa08c3171b8c53e3eb14f34063.

MBEVocoder.cpp: In constructor ‘MBEVocoder::MBEVocoder()’:
MBEVocoder.cpp:31:2: error: ‘md380_init’ was not declared in this scope
  md380_init();
  ^~~~~~~~~~
MBEVocoder.cpp:31:2: note: suggested alternative: ‘md380_encode’
  md380_init();
  ^~~~~~~~~~
  md380_encode
make: *** [Makefile:18: MBEVocoder.o] Error 1

**Comment by nostar** [comment]
You need the latest md380_vocoder.

**Comment by K2IE** [comment]
Resolved by pulling latest md380_vocoder and reinstalling.
