### ISSUE TITLE
USRP2M17 does not reconnect

### ISSUE THREAD

**Issue by vk3jed** [juribeparada/MMDVM_CM#63]
If a network connection that USRP2M17 is running over is interrupted, or the reflector it's linked to is restarted, the reflector no longer recognises the connection and (correctly) issues a NAK, but USRP2M17 still believes it's connected.  Only way to restore connectivity is to restart USrP2M17, once the network or server issue is resolved, or after restarting the reflector.

**Comment by nostar** [comment]
All the M17 utils will reconnect now.

**Comment by vk3jed** [comment]
Sorry about the late reply, all working, thanks.  I'll close the issue.
