### ISSUE TITLE
USRP2DMR Build Fails

### ISSUE THREAD

**Issue by K2IE** [juribeparada/MMDVM_CM#67]
++ -g -O3 -Wall -std=c++0x -pthread -c -o MBEVocoder.o MBEVocoder.cpp
MBEVocoder.cpp: In constructor ‘MBEVocoder::MBEVocoder()’:
MBEVocoder.cpp:33:2: error: ‘md380_init’ was not declared in this scope
   33 |  md380_init();
      |  ^~~~~~~~~~
make: *** [Makefile:18: MBEVocoder.o] Error 1

**Comment by nostar** [comment]
You need the latest md380_vocoder.
