### ISSUE TITLE
"echo back" also with IPSC2 connection

### ISSUE THREAD

**Issue by ik5xmk** [juribeparada/MMDVM_CM#7]
Hi, 
using your latest version of YSF2DMR no problem with XLX link, but i have an "echo back" (short, 1 sec of ptt with latest callsign worked) when i connect YSF2DMR to IPSC2 server. If you need, link my TUSCANY server (ipsc.grupporadiofirenze.net) with your YSF. Thank you.
David IK5XMK

**Comment by juribeparada** [comment]
Hi, I tested with several IPSC2 servers, and I have not seen the issue you have. Even using your suggested server (ipsc.grupporadiofirenze.net), and I have not heard the "echo back". Are you sure you are using latest source code?

**Comment by ik5xmk** [comment]
Hi Andy, yes latest version, see ysf.grupporadiofirenze.net/ysf
This reflector is connected at the moment to XLX039/R, than XLX039/R to
IPSC2-TUSCANY, this to have a clear working situation, no "echo back".
If i connect IT GRF-YSF directly to IPSC2-TUSCANY (via YSF2DMR using TG2225
as default) and after XLX039/R, i have the "echo back" issue.
Can i dispose this link to help you in debugging ? please say to me when
you can try, about....
Thank you very much
David IK5XMK

Il giorno dom 7 ott 2018 alle ore 16:19 Andy CA6JAU <
notifications@github.com> ha scritto:

**Comment by ik5xmk** [comment]
Hi Andy, and thank you for your availability and kindness.

I understand that it is difficult to detect the problem, there are
different combinations and depends on the active (and quality) structure.

I try to expose as clearly as possible, obviously always showing the
availability to any test:

*Working situation*, but in my opinion more critical because everything is
entrusted to the transcoding of XLX and just a not perfect commitment on a
repeater that the transition between the systems does not happen:

IT GRF-YSF <=> XLX039 / R <=> IPSC2-TUSCANY (TG 2225)
                                               <=> BM 2222 IT (TG 2225)

(BM and IPSC2 each have their own link on XLX (the first in peer and the
second as MMDVM)
(ipsc.grupporadiofirenze.net)
(ysf.grupporadiofirenze.net/ysf)
(xlx039.grupporadiofirenze.net/dashboard)

*NOT working situation* ("back echo"), but in my opinion more suitable
because C4FM is directed to the DMR and finally the transcoding on XLX:

IT GRF-YSF <=> IPSC2-TUSCANY (TG 2225) <=> XLX039 / R <=> BM 2222 IT (TG
2225)

ALL Servers are in CLOUD (same datacenter)

These are the configurations of YSF2DMR.ini:

*[DMR Network]*
*Id=2225069*

*#comment if you don't want xlx connection*
*XLXFile=XLXHosts.txt*
*XLXReflector=039*
*XLXModule=R*
*Port=62030*

*# il TG di default*
*StartupDstId=2225*
*# For TG call: StartupPC=0*
*StartupPC=0*

*#de-comment if you want mmdvm connection to ipsc2*
*#Address=ipsc.grupporadiofirenze.net <http://ipsc.grupporadiofirenze.net>*
*#Port=55555*
*Password=PASSWORD*
*Options=StartRef=4000;TS1_1=;TS1_2=;TS1_3=;TS1_4=;TS1_5=;TS2_1=2225;TS2_2=;TS2_3=;TS2_4=;TS2_5;*

This is the FIRST situation, the SECOND (back echo) is the same, but with
XLX section commented and IPSC2 de-commented
Please say me it is OK for you.

Thank you very much, 73
David IK5XMK


Il giorno dom 7 ott 2018 alle ore 21:21 Andy CA6JAU <
notifications@github.com> ha scritto:

**Comment by juribeparada** [comment]
OK, now I understand. What happen if you disconnect the link between IPSC2-TUSCANY <=> XLX039 / R, in the second configuration?
I think now, after saw your information, I will need to enter to your server where YSF2DMR is located, using remote ssh. I think I can check tomorrow at night here in Chile. Contact me by email for the details.

**Comment by ik5xmk** [comment]
Hi, with this configuration no problem in this time. Thank you Andy.

TUSCANY MULTIPROTOCOL INTERLINK

****** XLX039 - module R TRANSCODE
       |
       |
       |<---------- #26045 IT GRF-YSF REFL C4FM 
       |            YSF2DMR sw link TG 9                  
       |
       |<---------- BM 2222 TG 2225 DMR
       |            sw peer connection
       |
       |<---------- IPSC2-TUSCANY TG 2225 DMR <----- IPSC2-TUSCANY2 / DMRPlus net
       |            sw mmdvm connection
       |
       |<---------- DSTAR Repetears (IR5AY - IR5AF - all module R)
       |            sw ircddbgateway connection (DExtra,DPLus,DCS)
       |
       |<---------- DSTAR STARNET SERVER 395 A
       |            sw stn DExtra connection
       |
       \
