### ISSUE TITLE
YSF2DMR no receive audio

### ISSUE THREAD

**Issue by gekkehenkienl** [juribeparada/MMDVM_CM#8]
I cross compiled the MMDVM suite to MT7688 (OpenWRT).

MMDVMHost is working,
YSFGateway is working.
YSFParrot is working.

I am trying to run YSF2DMR now.
It compiled fine.
It starts on the MT7688 router.
Audio from YSF(handheld) to hotspot to DMR (Brandmeister) is working fine.
Audio from DMR to hotspot to YSF(handheld) is not working. The hotspot sends and outputs digital data, but my handheld (FT70d) is not accepting the traffic as audiostream.

I can replace the YSF2DMR daemon with YSFParrot on the same port, that is working as expected.

Any ideas how to troubleshoot this ?

Thanks,
Harold.

**Comment by gekkehenkienl** [comment]
Some additional info:
Just tried to use DMR through mmdvmhost.
That works fine.

DMR(Handheld) to hotspot to DMR (Brandmeister). Works fine.

Harold.

**Comment by juribeparada** [comment]
Hi Harold, sorry, but I don't have any OpenWRT compatible device in this moment for testing, I can't help, but maybe others can. Just to be sure, did you try YSF2DMR in another proved device like RPi or any PC? (just to check the configuration is OK).

**Comment by shawnchain** [comment]
YSF2P25 works fine on my mt7620 which has the same arch as mt7688. So I don't think there is a bug inside source code but please check your environment like the OpenWrt version, build sdk version, runtime libraries and most probably, the configuration files...

**Comment by gekkehenkienl** [comment]
Hi all,

Thanks for your response.

I did not try to use the current version of ysf2dmr on my raspberry. On that i currently run pi-star and that uses a older ysf2dmr version. Which is working fine. 
I use the same config file on the openwrt device.
I can try to compile this version for the raspi and check if that works. Not sure what it would take, but will try to do that tomorrow and report back the result.

For openwrt i run 18.0.1 which seems to be the latest version.
I did not use the sdk, but installed the compiler environment according to the guide on  openwrt.org.

Everything compiled without obvious errors and seems to run fine on the mt7688.
I never used ysf2p25 so i can not comment if that works. I will check if that works. Is there a remote parrot or alike that i can use to check ?

H.

**Comment by gekkehenkienl** [comment]
Did some tests today.

I compiled the YSF2DMR on my raspberry pi. The resulting file works fine.

I re-installed the openwrt-sdk tools and recompiled the MMDVM_CM suite. 
The resulting YSF2DMR is only working one-way.
1 : from YSF(FT70d) to hotspot to Brandmeister is working perfect.
2 : from Brandmeister to hotspot seems to work fine. The hotspot starts to TX on the frequency where my FT70d listens and if i monitor the channel (analog) then i hear digital noise.
My FT70d does receive the transmission but is not able to translate that from digital into analog audio.

I tried the YSF2P25 as well, but i am not sure if anyone was QRV to confirm my attempt.

@shawnchain : Are you able to compile and test the YSF2DMR functions on your openwrt hotspot ?

regards, Harold.

**Comment by gekkehenkienl** [comment]
I tested with a different mmdvm modem that was on my raspberry pi. 
Same result, so no audio on my handheld when receiving from the brandmeister network.

I suspect that it is caused by cross compiling the ysf2dmr to the openwrt environment.
It looks like the network data is not or incorrectly re-coded and send to the mmdvmhost.

I dont have a clue on how to find out what exactly happens. Any logging i can switch on so we can check what the data from brandmeister is, what the data send to mmdvmhost is and how to check if the transcoding is working correct ?

Thanks, Harold.

**Comment by gekkehenkienl** [comment]
Hi All.

I finally was able to get the YSF2DMR running on the openwrt router.
Not sure what was the culprit.

I recompiled under windows 10 (developer mode and installed ubuntu, then just follow the build instructions on openwrt.org)
It started working after i recompiled the YSFGateway with the same tools.

I would like to thank you for the software and help. I am really happy that it works now !

At least we know that it is working :-)

Harold.

**Comment by gekkehenkienl** [comment]
I found out that setting debug=1 gives me more info about the traffic streams.
Anyone able to make sense of the attached logfile ?

Harold.
[YSF2DMR-2018-10-15.log](https://github.com/juribeparada/MMDVM_CM/files/2477777/YSF2DMR-2018-10-15.log)

**Comment by gekkehenkienl** [comment]
Well.

I tested the YSF2P25 program. It behaves the same as YSF2DMR.
So it is not working correctly.


@shawnchain : 
Can you check if you are actually using the YSF2P25 on your openwrt mmdvm hotspot ?

Harold.

**Comment by shawnchain** [comment]
I have no idea about your case, nor error logs found there on your attachment. 
That's the bad of OpenWrt and Linux open-source world, you may need to put more diagnose code onto MMDVMHost and CM source code to find the root cause by your self.

**Comment by shawnchain** [comment]
Try out my build. 

[YSF2DMR_P25.bin.zip](https://github.com/juribeparada/MMDVM_CM/files/2478082/YSF2DMR_P25.bin.zip)

**Comment by gekkehenkienl** [comment]
Hello Shawn,

Thank you for the reply.
I have tried your build.
They behave exactly the same as mine.

Can you confirm that your build files are working on your system ?

MMDVMHost seems to run fine on my build and openwrt hotspot. DMR to Brandmeister and YSF to the YSF reflectors is working excellent. It's only the CM files that dont want to behave.

Harold.

**Comment by gekkehenkienl** [comment]
Did some more testing.

I installed openwrt on a orangepi.
Compiled the YSF2DMR for it.
started the YSF2DMR on the orangepi, configured to listen and talk to the remote MMDVM host on the MT7688 device (which i configured to use the YSF2DMR on the orangepi).

Same result as running the YSF2DMR on directly on the MT7688.

Next test: do the same from the pi-star device.

Harold.
