### ISSUE TITLE
DMR2YSF problem

### ISSUE THREAD

**Issue by SA7BNT** [juribeparada/MMDVM_CM#9]
Hello,
it´s a little bit suspect.
In my TG-YSFList.txt i have these entries.

26210;74154 #DE PEGASUS Multi-Bridge
262;62829 #DE Germany YSF262 BM263

When i make a GC on TG 262 on my TG 7 for DMR2YSF, it´s showing that i am using 256
MMDVMHost log
![bildschirmfoto 2018-10-09 um 13 01 49](https://user-images.githubusercontent.com/35367117/46665253-9d204880-cbc3-11e8-8280-3f615a8d1efd.png)
DMR2YSF log
![bildschirmfoto 2018-10-09 um 13 02 00](https://user-images.githubusercontent.com/35367117/46665254-9db8df00-cbc3-11e8-9068-a73daa791453.png)
The same problem is when im using my DMR2YSF TG7 it shows TG1 in the log.
DMR2YSF log
![bildschirmfoto 2018-10-09 um 13 06 12](https://user-images.githubusercontent.com/35367117/46665537-70b8fc00-cbc4-11e8-8465-17517a8939a2.png)
MMDVMHost log
![bildschirmfoto 2018-10-09 um 13 06 50](https://user-images.githubusercontent.com/35367117/46665538-71519280-cbc4-11e8-8391-3fee457c1a13.png)
Is it my config somewhere or is it a DMR2YSF issue??

BTW: when i´m using GC TG268 in the TG7 for DMR2YSF on my PD785, im on YSF ref. 62829 #DE Germany YSF262 BM263
Same when im getting voice via DMR2YSF from a ref. it shows TG13 not TG7 and in the radio i cant hear something. Which is christel clear why not.  
It seems that all is +6

**Comment by juribeparada** [comment]
Are you using DMRGateway?, if so, please test direct connection between MMDVMHost and DMR2YSF.

**Comment by SA7BNT** [comment]
Yes im running DMRGateway.
Just tested without DMRGateway and it seems to run fine without. So the problem is the DMRGateway??
Is that something you can fix or should i make a issue on the DMRGateway git??

![bildschirmfoto 2018-10-09 um 15 33 22](https://user-images.githubusercontent.com/35367117/46672934-f777d400-cbd8-11e8-9439-d020ba418908.png)

![bildschirmfoto 2018-10-09 um 15 33 37](https://user-images.githubusercontent.com/35367117/46672935-f9419780-cbd8-11e8-99b7-de609b14739a.png)

**Comment by juribeparada** [comment]
I don't know, it depends on DMRGateway configuration. Are you using Pi-Star?, if so, raise the issue on Pi-Star forum.

**Comment by SA7BNT** [comment]
No, no Pi* running here. 

DMRGateway and these Networks

XLX, BM, DMR+ 
and 
DMR2YSF

[DMR Network 3]
Name=DMR2YSF Crosslink
Enabled=1
Id=240706
Address=127.0.0.1
Port=62033
Local=62034
TGRewrite=1,7,2,1,99999
SrcRewrite=1,7,2,1,99999
PCRewrite=1,7,2,1,99999
Password="passw0rd"
Location=0
Debug=0

**Comment by juribeparada** [comment]
OK, I will need to test your configuration first

**Comment by juribeparada** [comment]
Not yet, but now looking at your configuration, I think your DMRGateway conf. is wrong, but all depends on what do you want. For example:

From: 1,7,2,1,99999, you actually are mapping:
Slot 1, TG7 -> Slot 2, TG1  (-6)
Slot 1, TG8 -> Slot 2, TG2 (-6)
...
Slot 1, TG262 -> Slot 2, TG256 (-6)

But you have TG262 in you TG-YSFList.txt (not TG256), that's why will not work.

Then there is not bug here, your problem is just your configuration.

**Comment by SA7BNT** [comment]
Damm shit. You are right. Will close the issue now for that is embarrassing. Sorry for waste your time.
